pointcloud_map_path: "/home/emre/Desktop/gnss_loc/src/maps/map.pcd"
pointcloud_map_metadata_path: /home/emre/Desktop/gnss_loc/src/maps/map_metadata.yaml"

map_projector_info_path: "/home/emre/Desktop/gnss_loc/src/maps/map_projector_info.yaml"
lanelet2_map_path: "/home/emre/Desktop/gnss_loc/src/maps/lane.osm"